
import { FlightData } from './types';

export const MOCK_FLIGHTS: FlightData[] = [
  {
    announcementText: "নমস্কার，尊敬的乘客們，早安！這裡是您的機長。本來是一個平常的飛行，但今早我們給達卡機場的工作人員帶來了一點小驚喜，我們比預計時間提前降落了！這座城市正以親切的笑容和清新的清晨空氣迎接我們。達卡現在的氣溫宜人，溫暖的陽光將是您今天探索這座城市的完美夥伴。",
    appId: "default-app-id-worldclock-history",
    city: "Dhaka",
    city_zh: "達卡",
    climateZoneName: "沙漠暖陽",
    country: "Bangladesh",
    country_iso_code: "BD",
    country_zh: "孟加拉",
    dataIdentifier: "sleep_1767425489802",
    deviceType: "raspberry_pi_sleep_flight",
    direction: 3,
    flightFeedback: "4",
    greeting: "",
    groupName: "Pi",
    imageUrl: "https://picsum.photos/seed/dhaka/800/600",
    isWormhole: false,
    language: "",
    languageCode: "",
    latitude: 23.81,
    longitude: 90.413,
    localTime: "2026-01-03T07:31:29.802Z",
    plannedMinutes: 360,
    punctuality: "EARLY",
    recordedAt: "2026-01-03T15:31:32Z",
    recordedDateString: "2026-01-03",
    sleepDuration: 2,
    timezone: "UTC",
    userDisplayName: "Pi User",
    wakeTime: "2026-01-03T07:31:29.802Z",
  },
  {
    announcementText: "Ladies and Gentlemen, we have just landed in Tokyo Haneda. The local time is 6:15 AM. We are exactly on schedule. Thank you for choosing Sleep Airline.",
    appId: "default-app-id-worldclock-history",
    city: "Tokyo",
    city_zh: "東京",
    climateZoneName: "海洋氣候",
    country: "Japan",
    country_iso_code: "JP",
    country_zh: "日本",
    dataIdentifier: "sleep_1767425489803",
    deviceType: "raspberry_pi_sleep_flight",
    direction: 1,
    flightFeedback: "5",
    greeting: "",
    groupName: "Pi",
    imageUrl: "https://picsum.photos/seed/tokyo/800/600",
    isWormhole: false,
    language: "",
    languageCode: "",
    latitude: 35.6762,
    longitude: 139.6503,
    localTime: "2026-01-02T06:15:00.000Z",
    plannedMinutes: 480,
    punctuality: "ON TIME",
    recordedAt: "2026-01-02T14:15:00Z",
    recordedDateString: "2026-01-02",
    sleepDuration: 8,
    timezone: "JST",
    userDisplayName: "Pi User",
    wakeTime: "2026-01-02T06:15:00.000Z",
  },
  {
    announcementText: "Welcome to London Heathrow. We apologize for the slight delay due to high-altitude winds, but we hope you enjoyed your extended rest.",
    appId: "default-app-id-worldclock-history",
    city: "London",
    city_zh: "倫敦",
    climateZoneName: "溫帶海洋",
    country: "United Kingdom",
    country_iso_code: "GB",
    country_zh: "英國",
    dataIdentifier: "sleep_1767425489804",
    deviceType: "raspberry_pi_sleep_flight",
    direction: 4,
    flightFeedback: "3",
    greeting: "",
    groupName: "Pi",
    imageUrl: "https://picsum.photos/seed/london/800/600",
    isWormhole: false,
    language: "",
    languageCode: "",
    latitude: 51.5074,
    longitude: -0.1278,
    localTime: "2025-12-31T23:59:00.000Z",
    plannedMinutes: 540,
    punctuality: "DELAYED",
    recordedAt: "2026-01-01T08:00:00Z",
    recordedDateString: "2025-12-31",
    sleepDuration: 9,
    timezone: "GMT",
    userDisplayName: "Pi User",
    wakeTime: "2025-12-31T23:59:00.000Z",
  },
  {
    announcementText: "Buenos Aires greets you with a warm breeze. We've arrived ahead of schedule, allowing you more time to explore this vibrant city.",
    appId: "default-app-id-worldclock-history",
    city: "Buenos Aires",
    city_zh: "布宜諾斯艾利斯",
    climateZoneName: "亞熱帶",
    country: "Argentina",
    country_iso_code: "AR",
    country_zh: "阿根廷",
    dataIdentifier: "sleep_1767425489805",
    deviceType: "raspberry_pi_sleep_flight",
    direction: 2,
    flightFeedback: "5",
    greeting: "",
    groupName: "Pi",
    imageUrl: "https://picsum.photos/seed/buenos/800/600",
    isWormhole: false,
    language: "",
    languageCode: "",
    latitude: -34.6037,
    longitude: -58.3816,
    localTime: "2025-12-28T10:30:00.000Z",
    plannedMinutes: 600,
    punctuality: "EARLY",
    recordedAt: "2025-12-28T18:30:00Z",
    recordedDateString: "2025-12-28",
    sleepDuration: 10,
    timezone: "ART",
    userDisplayName: "Pi User",
    wakeTime: "2025-12-28T10:30:00.000Z",
  }
];
